<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress.com" created="2021-06-03 20:15"-->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>InfoTech Services 86</title>
	<link>https://mediatek86.wordpress.com</link>
	<description>Besoin d’un site internet, d’un site marchand ? D’un hébergement web fiable ?  Besoin d&#039;externaliser la gestion et la maintenance de votre parc informatique, la gestion de vos serveurs d&#039;entreprise ?  Vous êtes au bon endroit !</description>
	<pubDate>Thu, 03 Jun 2021 20:15:46 +0000</pubDate>
	<language></language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://wordpress.com/</wp:base_site_url>
	<wp:base_blog_url>https://mediatek86.wordpress.com</wp:base_blog_url>

	<wp:author><wp:author_id>205059850</wp:author_id><wp:author_login><![CDATA[ninihan]]></wp:author_login><wp:author_email><![CDATA[betulcolak361@gmail.com]]></wp:author_email><wp:author_display_name><![CDATA[ninihan]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

	<wp:category><wp:term_id>6325</wp:term_id><wp:category_nicename>non-classe</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Non classé]]></wp:cat_name>
</wp:category>
	<wp:term><wp:term_id>6328</wp:term_id><wp:term_taxonomy>nav_menu</wp:term_taxonomy><wp:term_slug><![CDATA[primary]]></wp:term_slug><wp:term_name><![CDATA[Primary]]></wp:term_name>
</wp:term>
	<wp:term><wp:term_id>6329</wp:term_id><wp:term_taxonomy>nav_menu</wp:term_taxonomy><wp:term_slug><![CDATA[social]]></wp:term_slug><wp:term_name><![CDATA[Social]]></wp:term_name>
</wp:term>

	<generator>http://wordpress.com/</generator>
<image>
		<url>http://s0.wp.com/i/buttonw-com.png</url>
		<title>InfoTech Services 86</title>
		<link>https://mediatek86.wordpress.com</link>
	</image>
		
	<item>
		<title>Blog</title>
		<link>https://mediatek86.wordpress.com/?page_id=7</link>
		<pubDate>Thu, 03 Jun 2021 17:06:25 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?page_id=7</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:cover {"url":"https:\/\/mediatek86.files.wordpress.com\/2021\/06\/qi-bin-w4hbafegiac-unsplash.jpg","id":26,"dimRatio":10,"align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-10 has-background-dim" style="background-image:url('https://mediatek86.files.wordpress.com/2021/06/qi-bin-w4hbafegiac-unsplash.jpg');"><div class="wp-block-cover__inner-container"></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":64,"className":"desktop-only"} -->
<div style="height:64px;" aria-hidden="true" class="wp-block-spacer desktop-only"></div>
<!-- /wp:spacer -->

<!-- wp:a8c/blog-posts {"moreButton":true,"showAvatar":false,"postsToShow":10} /-->

<!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide" />
<!-- /wp:separator -->

<!-- wp:heading {"align":"left","level":3} -->
<h3 class="has-text-align-left">Abonnez-vous à mon blog</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left">Recevez directement le nouveau contenu dans votre boîte de réception.</p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/subscriptions -->
<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Souscrire" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
<!-- /wp:jetpack/subscriptions -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>7</wp:post_id>
		<wp:post_date>2021-06-03 18:06:25</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:25</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>blog__trashed</wp:post_name>
		<wp:status>trash</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_status</wp:meta_key>
			<wp:meta_value><![CDATA[publish]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[blog]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_checklist_post_type</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_time</wp:meta_key>
			<wp:meta_value><![CDATA[1622741862]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_desired_post_slug</wp:meta_key>
			<wp:meta_value><![CDATA[blog]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Contact</title>
		<link>https://mediatek86.wordpress.com/?page_id=8</link>
		<pubDate>Thu, 03 Jun 2021 17:06:24 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?page_id=8</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left">Don't hesitate to reach out with the contact information below, or send a message using the form.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32,"className":"desktop-only"} -->
<div style="height:32px;" aria-hidden="true" class="wp-block-spacer desktop-only"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","className":"has-2-columns"} -->
<div class="wp-block-columns alignwide has-2-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"align":"left"} -->
<h2 class="has-text-align-left">Contactez-nous</h2>
<!-- /wp:heading -->

<!-- wp:jetpack/contact-info -->
<div class="wp-block-jetpack-contact-info"><!-- wp:jetpack/address {"address":"10 Street Road","city":"City","postal":"10100","country":"USA"} -->
<div class="wp-block-jetpack-address"><div class="jetpack-address__address jetpack-address__address1">10 Street Road</div><div><span class="jetpack-address__city">City</span>, <span class="jetpack-address__region"></span> <span class="jetpack-address__postal">10100</span></div><div class="jetpack-address__country">USA</div></div>
<!-- /wp:jetpack/address -->

<!-- wp:jetpack/email {"email":"myemail@example.com"} -->
<div class="wp-block-jetpack-email"><a href="mailto:myemail@example.com">myemail@example.com</a></div>
<!-- /wp:jetpack/email -->

<!-- wp:jetpack/phone {"phone":"(123) 456-7890"} -->
<div class="wp-block-jetpack-phone"><a href="tel:1234567890">(123) 456-7890</a></div>
<!-- /wp:jetpack/phone --></div>
<!-- /wp:jetpack/contact-info -->

<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link-facebook /-->

<!-- wp:social-link-twitter /-->

<!-- wp:social-link-instagram {"url":"instagram.com"} /-->

<!-- wp:social-link-linkedin /-->

<!-- wp:social-link-youtube /-->

<!-- wp:social-link-facebook /-->

<!-- wp:social-link-facebook {"url":"facebook.com"} /-->

<!-- wp:social-link-twitter {"url":"twitter.com"} /-->

<!-- wp:social-link-wordpress {"url":"wordpress.com"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"align":"left"} -->
<h2 class="has-text-align-left">Envoyez-nous un message</h2>
<!-- /wp:heading -->

<!-- wp:jetpack/contact-form -->
<!-- wp:jetpack/field-name {"required":true} /-->

<!-- wp:jetpack/field-email {"label":"Email","required":true} /-->

<!-- wp:jetpack/field-url /-->

<!-- wp:jetpack/field-textarea {"required":true} /-->
<!-- /wp:jetpack/contact-form --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>8</wp:post_id>
		<wp:post_date>2021-06-03 18:06:24</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:24</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>contact__trashed</wp:post_name>
		<wp:status>trash</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[contact]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_checklist_post_type</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_status</wp:meta_key>
			<wp:meta_value><![CDATA[publish]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_time</wp:meta_key>
			<wp:meta_value><![CDATA[1622741901]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_desired_post_slug</wp:meta_key>
			<wp:meta_value><![CDATA[contact]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>À propos</title>
		<link>https://mediatek86.wordpress.com/?page_id=9</link>
		<pubDate>Thu, 03 Jun 2021 17:06:23 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?page_id=9</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:spacer {"height":20} -->
<div style="height:20px;" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><div class="wp-block-group__inner-container"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":3,"column1DesktopOffset":1,"column1TabletSpan":3,"column1MobileSpan":4,"column2DesktopSpan":6,"column2DesktopOffset":1,"column2TabletSpan":5,"column2MobileSpan":4,"column3DesktopOffset":3,"column3TabletOffset":1,"className":""} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-3 column1-desktop-grid__start-2 column1-desktop-grid__row-1 column2-desktop-grid__span-6 column2-desktop-grid__start-6 column2-desktop-grid__row-1 column1-tablet-grid__span-3 column1-tablet-grid__row-1 column2-tablet-grid__span-5 column2-tablet-grid__start-4 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"id":698,"sizeSlug":"full","className":"is-style-circle-mask"} -->
<figure class="wp-block-image size-full is-style-circle-mask"><img src="https://mediatek86.files.wordpress.com/2021/06/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg" alt="" class="wp-image-698" /></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2>C’est peut-être le bon endroit pour vous présenter et votre site ou insérer quelques crédits.</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Ceci est un exemple de page « À propos ». À la différence des articles, les pages sont plutôt destinées à du contenu dont vous souhaitez qu’il soit toujours facilement accessible, comme votre présentation ou vos coordonnées. Cliquez sur le lien de modification pour modifier cette page ou <a href="//wordpress.com/page">ajouter une autre page</a>.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div></div>
<!-- /wp:group -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>9</wp:post_id>
		<wp:post_date>2021-06-03 18:06:23</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:23</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>about__trashed</wp:post_name>
		<wp:status>trash</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[about-3]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_checklist_post_type</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_status</wp:meta_key>
			<wp:meta_value><![CDATA[publish]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_trash_meta_time</wp:meta_key>
			<wp:meta_value><![CDATA[1622745176]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_desired_post_slug</wp:meta_key>
			<wp:meta_value><![CDATA[about]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Présentation personnelle (exemple d’article)</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/example-post-3/</link>
		<pubDate>Thu, 03 Jun 2021 17:06:22 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?p=10</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p><em>Voici un exemple d’article, publié initialement dans le cadre de la </em><a href="https://dailypost.wordpress.com/blogging-university/"><em>Blogging University</em></a><em>. Inscrivez-vous à l’un de nos dix programmes et lancez votre blog.</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous allez publier un article aujourd’hui. Ne vous inquiétez pas pour l’apparence de votre blog. Ne vous inquiétez pas si vous ne lui avez pas encore donné de nom ou si vous vous sentez dépassé. Cliquez simplement sur le bouton « Nouvel article » et dites-nous pourquoi vous êtes ici.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Quel est votre objectif ? </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Vos nouveaux lecteurs ont besoin de contexte. De quoi parlerez-vous ? Pourquoi devraient-ils lire votre blog ?</li><li>Cela vous aidera à vous concentrer sur vos idées à propos de votre blog et sur la façon dont vous souhaitez le développer. </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>L’article peut être court ou long, contenir une introduction personnelle sur votre vie, décrire la mission de votre blog, présenter un manifeste pour l’avenir ou énoncer simplement vos sujets de publication.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Pour vous aider à commencer, voici quelques questions : </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Pourquoi créez-vous un blog public au lieu de tenir un journal personnel ?</li><li>Quels seront les thèmes que vous aborderez ?</li><li>Quelle est la cible privilégiée de votre blog ?</li><li>Si votre blog passe la première année avec succès, qu’espérez-vous avoir accompli ? </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Répondre à ces questions ne vous enferme pas définitivement dans une voie. Ce qui est magnifique avec les blogs, c’est qu’ils sont en constante évolution au fur et à mesure de vos apprentissages, de votre développement et des interactions avec autrui. Il est toutefois opportun de savoir où et pourquoi vous vous lancez. L’articulation de vos objectifs peut simplement contribuer à apporter de nouvelles idées d’articles.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous ne savez pas trop comment commencer ? Écrivez simplement la première chose qui vous passe par la tête. Anne Lamott, auteur d’un excellent livre sur le processus d’écriture, affirme qu’il est nécessaire de s’autoriser un « premier jet bordélique ». C’est un enseignement essentiel : commencez par écrire, vous vous occuperez de retoucher votre texte plus tard.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Une fois que vous êtes prêt à publier, attribuez à votre article trois à cinq étiquettes qui décrivent son sujet : littérature, photographie, fiction, parentalité, alimentation, voitures, films, sports, etc. Ces étiquettes aideront les internautes intéressés par ces sujets à vous trouver dans le Lecteur. Veillez à ce que l’une de ces étiquettes soit « zerotohero », afin que les nouveaux blogueurs puissent vous trouver également.</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>10</wp:post_id>
		<wp:post_date>2021-06-03 18:06:22</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:22</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>example-post-3</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>post</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="category" nicename="non-classe"><![CDATA[Non classé]]></category>
		<wp:postmeta>
			<wp:meta_key>_headstart_post</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wpas_skip_all_services</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Présentation personnelle (exemple d’article)</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/example-post-2/</link>
		<pubDate>Thu, 03 Jun 2021 17:06:21 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?p=11</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p><em>Voici un exemple d’article, publié initialement dans le cadre de la </em><a href="https://dailypost.wordpress.com/blogging-university/"><em>Blogging University</em></a><em>. Inscrivez-vous à l’un de nos dix programmes et lancez votre blog.</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous allez publier un article aujourd’hui. Ne vous inquiétez pas pour l’apparence de votre blog. Ne vous inquiétez pas si vous ne lui avez pas encore donné de nom ou si vous vous sentez dépassé. Cliquez simplement sur le bouton « Nouvel article » et dites-nous pourquoi vous êtes ici.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Quel est votre objectif ? </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Vos nouveaux lecteurs ont besoin de contexte. De quoi parlerez-vous ? Pourquoi devraient-ils lire votre blog ?</li><li>Cela vous aidera à vous concentrer sur vos idées à propos de votre blog et sur la façon dont vous souhaitez le développer. </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>L’article peut être court ou long, contenir une introduction personnelle sur votre vie, décrire la mission de votre blog, présenter un manifeste pour l’avenir ou énoncer simplement vos sujets de publication.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Pour vous aider à commencer, voici quelques questions : </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Pourquoi créez-vous un blog public au lieu de tenir un journal personnel ?</li><li>Quels seront les thèmes que vous aborderez ?</li><li>Quelle est la cible privilégiée de votre blog ?</li><li>Si votre blog passe la première année avec succès, qu’espérez-vous avoir accompli ? </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Répondre à ces questions ne vous enferme pas définitivement dans une voie. Ce qui est magnifique avec les blogs, c’est qu’ils sont en constante évolution au fur et à mesure de vos apprentissages, de votre développement et des interactions avec autrui. Il est toutefois opportun de savoir où et pourquoi vous vous lancez. L’articulation de vos objectifs peut simplement contribuer à apporter de nouvelles idées d’articles.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous ne savez pas trop comment commencer ? Écrivez simplement la première chose qui vous passe par la tête. Anne Lamott, auteur d’un excellent livre sur le processus d’écriture, affirme qu’il est nécessaire de s’autoriser un « premier jet bordélique ». C’est un enseignement essentiel : commencez par écrire, vous vous occuperez de retoucher votre texte plus tard.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Une fois que vous êtes prêt à publier, attribuez à votre article trois à cinq étiquettes qui décrivent son sujet : littérature, photographie, fiction, parentalité, alimentation, voitures, films, sports, etc. Ces étiquettes aideront les internautes intéressés par ces sujets à vous trouver dans le Lecteur. Veillez à ce que l’une de ces étiquettes soit « zerotohero », afin que les nouveaux blogueurs puissent vous trouver également.</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>11</wp:post_id>
		<wp:post_date>2021-06-03 18:06:21</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:21</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>example-post-2</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>post</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="category" nicename="non-classe"><![CDATA[Non classé]]></category>
		<wp:postmeta>
			<wp:meta_key>_headstart_post</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wpas_skip_all_services</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Présentation personnelle (exemple d’article)</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/example-post/</link>
		<pubDate>Thu, 03 Jun 2021 17:06:20 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?p=12</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p><em>Voici un exemple d’article, publié initialement dans le cadre de la </em><a href="https://dailypost.wordpress.com/blogging-university/"><em>Blogging University</em></a><em>. Inscrivez-vous à l’un de nos dix programmes et lancez votre blog.</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous allez publier un article aujourd’hui. Ne vous inquiétez pas pour l’apparence de votre blog. Ne vous inquiétez pas si vous ne lui avez pas encore donné de nom ou si vous vous sentez dépassé. Cliquez simplement sur le bouton « Nouvel article » et dites-nous pourquoi vous êtes ici.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Quel est votre objectif ? </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Vos nouveaux lecteurs ont besoin de contexte. De quoi parlerez-vous ? Pourquoi devraient-ils lire votre blog ?</li><li>Cela vous aidera à vous concentrer sur vos idées à propos de votre blog et sur la façon dont vous souhaitez le développer. </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>L’article peut être court ou long, contenir une introduction personnelle sur votre vie, décrire la mission de votre blog, présenter un manifeste pour l’avenir ou énoncer simplement vos sujets de publication.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Pour vous aider à commencer, voici quelques questions : </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Pourquoi créez-vous un blog public au lieu de tenir un journal personnel ?</li><li>Quels seront les thèmes que vous aborderez ?</li><li>Quelle est la cible privilégiée de votre blog ?</li><li>Si votre blog passe la première année avec succès, qu’espérez-vous avoir accompli ? </li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Répondre à ces questions ne vous enferme pas définitivement dans une voie. Ce qui est magnifique avec les blogs, c’est qu’ils sont en constante évolution au fur et à mesure de vos apprentissages, de votre développement et des interactions avec autrui. Il est toutefois opportun de savoir où et pourquoi vous vous lancez. L’articulation de vos objectifs peut simplement contribuer à apporter de nouvelles idées d’articles.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Vous ne savez pas trop comment commencer ? Écrivez simplement la première chose qui vous passe par la tête. Anne Lamott, auteur d’un excellent livre sur le processus d’écriture, affirme qu’il est nécessaire de s’autoriser un « premier jet bordélique ». C’est un enseignement essentiel : commencez par écrire, vous vous occuperez de retoucher votre texte plus tard.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Une fois que vous êtes prêt à publier, attribuez à votre article trois à cinq étiquettes qui décrivent son sujet : littérature, photographie, fiction, parentalité, alimentation, voitures, films, sports, etc. Ces étiquettes aideront les internautes intéressés par ces sujets à vous trouver dans le Lecteur. Veillez à ce que l’une de ces étiquettes soit « zerotohero », afin que les nouveaux blogueurs puissent vous trouver également.</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>12</wp:post_id>
		<wp:post_date>2021-06-03 18:06:20</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:06:20</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>example-post</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>post</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="category" nicename="non-classe"><![CDATA[Non classé]]></category>
		<wp:postmeta>
			<wp:meta_key>_headstart_post</wp:meta_key>
			<wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wpas_skip_all_services</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title></title>
		<link>https://mediatek86.wordpress.com/2021/06/03/20/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/20/</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>20</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>20</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>1</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="primary"><![CDATA[Primary]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[6]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[page]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title></title>
		<link>https://mediatek86.wordpress.com/2021/06/03/21/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/21/</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>21</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>21</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>2</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="primary"><![CDATA[Primary]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[7]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[page]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Facebook</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/facebook/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/facebook/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>24</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>facebook</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>1</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="social"><![CDATA[Social]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[24]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[https://facebook.com]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Twitter</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/twitter/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/twitter/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>25</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>twitter</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>2</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="social"><![CDATA[Social]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[25]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[https://twitter.com]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Instagram</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/instagram/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/instagram/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>26</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>instagram</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>3</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="social"><![CDATA[Social]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[26]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[https://instagram.com]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Pinterest</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/pinterest/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/pinterest/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>27</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>pinterest</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>4</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="social"><![CDATA[Social]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[27]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[https://pinterest.com]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>WordPress</title>
		<link>https://mediatek86.wordpress.com/2021/06/03/wordpress/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/wordpress/</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>28</wp:post_id>
		<wp:post_date>2021-06-03 18:11:27</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>wordpress</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>5</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="social"><![CDATA[Social]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[28]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[https://wordpress.com]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Placeholder Image</title>
		<link>https://mediatek86.wordpress.com/placeholder-image/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:29 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/qi-bin-w4hbafegiac-unsplash.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>29</wp:post_id>
		<wp:post_date>2021-06-03 19:11:29</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:29</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>placeholder-image</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/qi-bin-w4hbafegiac-unsplash.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/qi-bin-w4hbafegiac-unsplash.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:1600;s:6:"height";i:1066;s:4:"file";s:104:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/qi-bin-w4hbafegiac-unsplash.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:50995;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Placeholder Image</title>
		<link>https://mediatek86.wordpress.com/placeholder-image-2/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:33 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>32</wp:post_id>
		<wp:post_date>2021-06-03 19:11:33</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:33</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>placeholder-image-2</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:1560;s:6:"height";i:1560;s:4:"file";s:114:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/rachel-pfuetzner-0fn7fxv1ewa-unsplash.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"1";s:8:"keywords";a:0:{}}s:8:"filesize";i:56258;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>fond-technologie-violet_79603-294</title>
		<link>https://mediatek86.wordpress.com/fond-technologie-violet_79603-294/</link>
		<pubDate>Thu, 03 Jun 2021 17:21:04 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/fond-technologie-violet_79603-294.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>38</wp:post_id>
		<wp:post_date>2021-06-03 19:21:04</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:21:04</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>fond-technologie-violet_79603-294</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/fond-technologie-violet_79603-294.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/fond-technologie-violet_79603-294.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:626;s:6:"height";i:417;s:4:"file";s:110:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/fond-technologie-violet_79603-294.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:57804;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>cropped-fond-technologie-violet_79603-294.jpg</title>
		<link>https://mediatek86.wordpress.com/cropped-fond-technologie-violet_79603-294-jpg/</link>
		<pubDate>Thu, 03 Jun 2021 17:21:11 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.files.wordpress.com/2021/06/cropped-fond-technologie-violet_79603-294.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>39</wp:post_id>
		<wp:post_date>2021-06-03 19:21:11</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:21:11</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>cropped-fond-technologie-violet_79603-294-jpg</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/cropped-fond-technologie-violet_79603-294.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-fond-technologie-violet_79603-294.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_context</wp:meta_key>
			<wp:meta_value><![CDATA[custom-header]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:7:{s:5:"width";i:1200;s:6:"height";i:500;s:4:"file";s:118:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-fond-technologie-violet_79603-294.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:65875;s:17:"attachment_parent";i:38;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_custom_header_last_used_pub/snaps</wp:meta_key>
			<wp:meta_value><![CDATA[1622740875]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_is_custom_header</wp:meta_key>
			<wp:meta_value><![CDATA[pub/snaps]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>city-scape-vector-illustration-vector-city-scape-purple-background_99338-27</title>
		<link>https://mediatek86.wordpress.com/city-scape-vector-illustration-vector-city-scape-purple-background_99338-27/</link>
		<pubDate>Thu, 03 Jun 2021 17:23:26 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>41</wp:post_id>
		<wp:post_date>2021-06-03 19:23:26</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:23:26</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>city-scape-vector-illustration-vector-city-scape-purple-background_99338-27</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:626;s:6:"height";i:715;s:4:"file";s:152:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:59582;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg</title>
		<link>https://mediatek86.wordpress.com/cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27-jpg/</link>
		<pubDate>Thu, 03 Jun 2021 17:23:34 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.files.wordpress.com/2021/06/cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>42</wp:post_id>
		<wp:post_date>2021-06-03 19:23:34</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:23:34</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27-jpg</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_context</wp:meta_key>
			<wp:meta_value><![CDATA[custom-header]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:7:{s:5:"width";i:1200;s:6:"height";i:500;s:4:"file";s:160:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-city-scape-vector-illustration-vector-city-scape-purple-background_99338-27.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:30997;s:17:"attachment_parent";i:41;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_custom_header_last_used_pub/snaps</wp:meta_key>
			<wp:meta_value><![CDATA[1622741015]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_is_custom_header</wp:meta_key>
			<wp:meta_value><![CDATA[pub/snaps]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>max-ostrozhinskiy-218836-unsplash-copy11</title>
		<link>https://mediatek86.wordpress.com/max-ostrozhinskiy-218836-unsplash-copy11/</link>
		<pubDate>Thu, 03 Jun 2021 17:23:48 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/max-ostrozhinskiy-218836-unsplash-copy11.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>43</wp:post_id>
		<wp:post_date>2021-06-03 19:23:48</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:23:48</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>max-ostrozhinskiy-218836-unsplash-copy11</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/max-ostrozhinskiy-218836-unsplash-copy11.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/max-ostrozhinskiy-218836-unsplash-copy11.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:2952;s:6:"height";i:1958;s:4:"file";s:117:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/max-ostrozhinskiy-218836-unsplash-copy11.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:293873;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>Accueil</title>
		<link>https://mediatek86.wordpress.com/</link>
		<pubDate>Thu, 03 Jun 2021 18:33:01 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?page_id=6</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:cover {"url":"https:\/\/mediatek86.files.wordpress.com\/2021\/06\/cropped-awzdv5b.jpg","id":47,"dimRatio":10,"minHeight":435,"minHeightUnit":"px","align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-10 has-background-dim" style="min-height:435px;"><img class="wp-block-cover__image-background wp-image-47" alt="" src="https://mediatek86.files.wordpress.com/2021/06/cropped-awzdv5b.jpg" data-object-fit="cover" /><div class="wp-block-cover__inner-container"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":8,"column1DesktopOffset":2,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":4,"className":"column1-desktop-grid__span-8 column1-desktop-grid__start-3 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-8 column1-desktop-grid__start-3 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading {"textAlign":"center","level":1} -->
<h1 class="has-text-align-center">Bienvenue !</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center"><strong>InfoTech Services 86 (ITS 86), est une Entreprise de Services Numériques (ESN) spécialisée dans le développement informatique (applications de bureau, web, mobile), l’hébergement de site web, l’infogérance, la gestion de parc informatique et l’ingénierie système et réseau.&nbsp;</strong></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link" href="http://learn.wordpress.com" title="learn.wordpress.com">En savoir plus</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"align":"full","backgroundColor":"background"} -->
<div class="wp-block-group alignfull has-background-background-color has-background"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":6,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":12,"className":""} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-6 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2><span class="has-inline-color has-black-color">Activité principale</span></h2>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>Proposer des solutions d'hébergements sur des serveurs dédiés</h2>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->

<!-- wp:jetpack/layout-grid {"column1DesktopSpan":6,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":12,"className":"column1-desktop-grid__span-6 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-6 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2>Ingénierie logicielle</h2>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>Ingénierie système et réseau</h2>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>Conseil et Démarches</h2>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","backgroundColor":"foreground-dark"} -->
<div class="wp-block-group alignfull has-foreground-dark-background-color has-background"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":3,"column1DesktopOffset":2,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":5,"column2TabletSpan":4,"column2MobileSpan":4,"column3DesktopOffset":3,"className":"column1-desktop-grid__span-3 column1-desktop-grid__start-3 column1-desktop-grid__row-1 column2-desktop-grid__span-5 column2-desktop-grid__start-6 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-3 column1-desktop-grid__start-3 column1-desktop-grid__row-1 column2-desktop-grid__span-5 column2-desktop-grid__start-6 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:quote -->
<blockquote class="wp-block-quote"><p>Recevez directement le nouveau contenu dans votre boîte de réception.</p></blockquote>
<!-- /wp:quote --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:jetpack/subscriptions {"buttonOnNewLine":true,"submitButtonText":"Souscrire","buttonBackgroundColor":"primary","textColor":"background"} -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline wp-block-jetpack-subscriptions__use-newline">[jetpack_subscription_form show_subscribers_total="false" button_on_newline="true" submit_button_text="Souscrire" custom_font_size="16px" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="has-text-color has-background-color has-background has-primary-background-color" email_field_classes="" show_only_email_and_button="true"]</div>
<!-- /wp:jetpack/subscriptions --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div>
<!-- /wp:group -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>6</wp:post_id>
		<wp:post_date>2021-06-03 20:33:01</wp:post_date>
		<wp:post_date_gmt>2021-06-03 18:33:01</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>home</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>1</wp:menu_order>
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>switch_like_status</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sharing_disabled</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_starter_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_rest_api_published</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_rest_api_client_id</wp:meta_key>
			<wp:meta_value><![CDATA[-1]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title></title>
		<link>https://mediatek86.wordpress.com/2021/06/03/22/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/22/</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>22</wp:post_id>
		<wp:post_date>2021-06-03 20:38:40</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>22</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>1</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="primary"><![CDATA[Primary]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[23]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[9]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[page]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title></title>
		<link>https://mediatek86.wordpress.com/2021/06/03/23/</link>
		<pubDate>Thu, 03 Jun 2021 17:11:27 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/23/</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>23</wp:post_id>
		<wp:post_date>2021-06-03 20:38:40</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:11:27</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>23</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>1</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="primary"><![CDATA[Primary]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[21]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[8]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[page]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>AWzDV5B</title>
		<link>https://mediatek86.wordpress.com/awzdv5b/</link>
		<pubDate>Thu, 03 Jun 2021 17:25:29 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">http://mediatek86.files.wordpress.com/2021/06/awzdv5b.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>46</wp:post_id>
		<wp:post_date>2021-06-03 19:25:29</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:25:29</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>awzdv5b</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/awzdv5b.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/awzdv5b.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";i:1920;s:6:"height";i:1080;s:4:"file";s:84:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/awzdv5b.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:16554;}]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>cropped-awzdv5b.jpg</title>
		<link>https://mediatek86.wordpress.com/cropped-awzdv5b-jpg/</link>
		<pubDate>Thu, 03 Jun 2021 17:25:38 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.files.wordpress.com/2021/06/cropped-awzdv5b.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>47</wp:post_id>
		<wp:post_date>2021-06-03 19:25:38</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:25:38</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>cropped-awzdv5b-jpg</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>https://mediatek86.files.wordpress.com/2021/06/cropped-awzdv5b.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-awzdv5b.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_context</wp:meta_key>
			<wp:meta_value><![CDATA[custom-header]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:7:{s:5:"width";i:1200;s:6:"height";i:500;s:4:"file";s:92:"/home/wpcom/public_html/wp-content/blogs.dir/f28/193983424/files/2021/06/cropped-awzdv5b.jpg";s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}s:8:"filesize";i:17538;s:17:"attachment_parent";i:46;}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_custom_header_last_used_pub/snaps</wp:meta_key>
			<wp:meta_value><![CDATA[1622741142]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_is_custom_header</wp:meta_key>
			<wp:meta_value><![CDATA[pub/snaps]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title>MediaTek86</title>
		<link>https://mediatek86.wordpress.com/portfolio/mediatek86/</link>
		<pubDate>Thu, 03 Jun 2021 17:43:11 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/?post_type=jetpack-portfolio&#038;p=53</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Le réseau des médiathèques de la Vienne, MediaTek86 a pour rôle de fédérer les prêts de livres, DVD et CD et de développer la médiathèque numérique pour l’ensemble des médiathèques du département.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p id="yui_3_17_2_1_1622741993445_52">Afin de donner plus d’attractivité aux médiathèques, MediaTek86 veut se développer selon deux axes :</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>enrichir ses services en offrant aux adhérents la possibilité d’emprunter des films en VOD ;</li><li>proposer, en complément de l’activité principale de la médiathèque, des formations aux outils numériques et des autoformations en ligne.</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><em>MediaTek86</em>&nbsp;gère le portail web unique, un véritable catalogue en ligne qui permet aux adhérents de réserver et d’emprunter plus de 200 000 documents (livres, journaux, CD, DVD, jeux), revues (400 titres de périodiques en ligne) et ressources numériques répartis dans différents lieux.&nbsp;<em>MediaTek86</em>&nbsp;est un réseau qui regroupe les responsables de chaque médiathèque, un chef de projet numérique, une chargée de communication numérique et un infographiste. Les projets numériques sont pilotés par le chef de projet numérique qui est chargé de la maîtrise d’ouvrage (MOA) auprès des ESN auxquelles&nbsp;<em>MediaTek86</em>&nbsp;fait appel pour la gestion du parc informatique des médiathèques, l’infogérance de son infrastructure système et réseau hébergée dans le cloud et le développement de son portail web et de ses applications internes.</p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Projet DIGIMEDIATEK86</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Dans chaque médiathèque, les employés du service administratif ou médiation culturelle disposent d'un poste informatique attitré, les employés du service prêt n’ont pas de poste attitré. Selon la fonction, les logiciels installés diffèrent mais ils sont tous dotés de Windows 10 Pro, d'un navigateur, d'un client de messagerie, de la suite Microsoft Office, d’un antivirus, d’un logiciel de sauvegarde, d’un accès sécurisé au portail web qui gère les prêts et les acquisitions. Les employés du service&nbsp;<strong>Médiation culturelle</strong>&nbsp;disposent en outre de plusieurs logiciels spécifiques liés à leurs activités de communication : Adobe Creative Suite avec logiciel de montage Vidéo.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>MediaTek86</em>&nbsp;souhaite fournir aux employés des médiathèques un ensemble de services identiques sur chaque site :</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>un service d’annuaire Active Directory hébergé dans le cloud Azure permet à tous les employés et responsables d’une médiathèque de se connecter aux services proposés par MediaTek86 ;</li><li>chaque employé dispose d’un compte d’utilisateur sur le domaine Active Directory de MediaTek86.</li><li>une solution logicielle de gestion d’incidents intégrée au portail web permet aux utilisateurs de créer des tickets de demande ou d’incidents.</li><li>un portail internet DigiMediaTek86 permettant la réservation de documents pour les prêts inter-médiathèque et l’accès aux prêts des adhérents (consultation, réservation, prolongation).</li></ul>
<!-- /wp:list -->

<!-- wp:heading -->
<h2>Service aux usagers</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>MediaTek86 souhaite fournir aux usagers (adhérents ou non) un ensemble de services numériques identiques sur chaque site :</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>les salles informatiques en libre-service ont une capacité de 12 personnes avec accès à Internet ;</li><li>un hotspot Wifi Public est accessible à tous les usagers de la médiathèque pour l’accès à Internet ;</li><li>des tablettes numériques et des liseuses sont disponibles en utilisation sur place, connectées au Wifi Public ;</li><li>l’accès à internet est disponible gratuitement à partir des postes en libre-service et des tablettes pour tout usager inscrit, avec possibilité d'impression sur les photocopieurs multifonctions du réseau Public ;</li><li>un accès au portail internet DigiMediaTek86 pour les adhérents depuis chez eux (consultation des prêts en cours, réservation de documents, prolongation d’un prêt…) et aux nouveaux services numériques proposés par MediaTek86 (notamment la VOD) ;</li><li>des formations au numérique en ligne et en présentiel dispensées par des associations locales ;</li><li>les formations en présentiel se déroulent dans la salle informatique en libre-service située dans certaines médiathèques. Chaque salle libre-service est équipée de 12 postes « stagiaires », 1 poste « formateur/employé », un photocopieur multifonctions (avec système de carte ou code pour le paiement).</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>53</wp:post_id>
		<wp:post_date>2021-06-03 19:43:11</wp:post_date>
		<wp:post_date_gmt>2021-06-03 17:43:11</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>mediatek86</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>jetpack-portfolio</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
			<wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_rest_api_published</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_rest_api_client_id</wp:meta_key>
			<wp:meta_value><![CDATA[-1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_publicize_job_id</wp:meta_key>
			<wp:meta_value><![CDATA[59170710548]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<item>
		<title></title>
		<link>https://mediatek86.wordpress.com/2021/06/03/63/</link>
		<pubDate>Thu, 03 Jun 2021 18:36:59 +0000</pubDate>
		<dc:creator>ninihan</dc:creator>
		<guid isPermaLink="false">https://mediatek86.wordpress.com/2021/06/03/63/</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>63</wp:post_id>
		<wp:post_date>2021-06-03 20:36:59</wp:post_date>
		<wp:post_date_gmt>2021-06-03 18:36:59</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>63</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>5</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="primary"><![CDATA[Primary]]></category>
		<wp:postmeta>
			<wp:meta_key>_publicize_pending</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[53]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[jetpack-portfolio]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_content</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
</channel>
</rss>
